### ISSUE TITLE
arm_now

### ISSUE THREAD

**Issue by nongiach** [genuinetools/www#3]
Hey,
I just saw your repo, very interesting !
I'm working on a tools that instantly deploys a virtual machine using qemu, you can choose the cpu arch that you want to emulate.
I was thinking that maybe it could join the Genuine Tools list, I can make all needed modifications so it fully follows the values.
What do you think ?

https://github.com/nongiach/arm_now

**Comment by jessfraz** [comment]
Thats cool thanks! Right now i dont have a way to add more repos to genuinetools but I will let you know when I come up with a process!!
